(*
   $Id: mkmodule.js,v 1.46 2010/02/04 16:48:02 robbod Exp $
   N - ISO/CD-TS - 10303- product_data_equivalence_definition - EXPRESS ARM*)
(* UNDER DEVELOPMENT *)
SCHEMA Product_data_equivalence_definition_arm;

  USE FROM Date_time_assignment_arm;

  USE FROM Person_organization_assignment_arm;

  TYPE Equivalence_date_or_date_time_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON Date_or_date_time_item WITH
    (Data_equivalence_definition);
  END_TYPE;

  TYPE Equivalence_organization_or_person_in_organization_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON Organization_or_person_in_organization_item WITH
    (Data_equivalence_definition);
  END_TYPE;
  
  TYPE Equivalence_product_data_select = EXTENSIBLE GENERIC_ENTITY SELECT;
  END_TYPE;

  TYPE Used_equivalence_representation_select = EXTENSIBLE GENERIC_ENTITY SELECT;
  END_TYPE;

  ENTITY Data_equivalence_definition;
      description : STRING;
  END_ENTITY;

  ENTITY Data_equivalence_definition_relationship;
      description                      : STRING;
      relating_data_quality_definition : Data_equivalence_definition;
      related_data_quality_definition  : Data_equivalence_definition;
  END_ENTITY;

  ENTITY Data_equivalence_definition_representation_relationship;
      description         : STRING;
      definition          : Data_equivalence_definition;
      used_representation : Used_equivalence_representation_select;
  END_ENTITY;

  ENTITY Product_data_and_data_equivalence_relationship;
      description  : STRING;
      product_data : Equivalence_product_data_select;
      data_quality : Data_equivalence_definition;
  END_ENTITY;

  ENTITY Software_for_data_equivalence_check;
      description      : STRING;
      software_name    : STRING;
      software_version : STRING;
      data_equivalence     : Data_equivalence_definition_representation_relationship;
  END_ENTITY;

END_SCHEMA;
